name: nurses_notes
description: A Flutter web app for Nursing Care Plans, Drug Studies, and Reflections.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  

  pdf: ^3.11.0
  printing: ^5.12.0

  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  cupertino_icons: ^1.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/icons/